spring.application.name=order-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/orderflow}
spring.datasource.username=${DB_USERNAME:orderflow}
spring.datasource.password=${DB_PASSWORD:orderflow}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration